In [3]:
import pandas as pd
import openpyxl

dado = r"CD2022_Populacao_2010_Compatibilizada_20231222.xlsx"

indicador_1 = pd.read_excel(dado, header=2)

indicador_1 = indicador_1.iloc[:,1:]

indicador_1 = indicador_1.loc[:,[
    "UF",
    "COD. UF",
    "COD. MUNIC",
    "NOME DO MUNICÍPIO",
    "População Município 2010\n(Sinopse)",
    "População 2010 (Alterações de Limites até 2022)1",
    "População Censo 2022"
]]

indicador_1.head()

,UF,COD. UF,COD. MUNIC,NOME DO MUNICÍPIO,População Município 2010\n(Sinopse),População 2010 (Alterações de Limites até 2022)1,População Censo 2022
0,RO,11.0,15.0,Alta Floresta D'Oeste,24392.0,24392.0,21494.0
1,RO,11.0,23.0,Ariquemes,90353.0,90353.0,96833.0
2,RO,11.0,31.0,Cabixi,6313.0,6313.0,5351.0
3,RO,11.0,49.0,Cacoal,78574.0,78574.0,86887.0
4,RO,11.0,56.0,Cerejeiras,17029.0,17029.0,15890.0

In [19]:
populacao_estado = (
    indicador_1.loc[:, [
        "UF",
        "População 2010 (Alterações de Limites até 2022)1",
        "População Censo 2022"
    ]]
    .groupby("UF")[[
        "População 2010 (Alterações de Limites até 2022)1",
        "População Censo 2022"
    ]]
    .sum()
    .reset_index()
)

# Calcular o crescimento
populacao_estado["Crescimento"] = (
    populacao_estado["População Censo 2022"] - populacao_estado["População 2010 (Alterações de Limites até 2022)1"]
)

# Organizar do maior para o menor crescimento
populacao_estado = populacao_estado.sort_values(
    "Crescimento",
    ascending=False
).reset_index(drop=True)

populacao_estado

,UF,População 2010 (Alterações de Limites até 2022)1,População Censo 2022,Crescimento
0,SP,41262199.0,44411238.0,3149039.0
1,SC,6248436.0,7610361.0,1361925.0
2,GO,6001789.0,7056495.0,1054706.0
3,PR,10444526.0,11444380.0,999854.0
4,MG,19597330.0,20539989.0,942659.0
5,MT,3035122.0,3658649.0,623527.0
6,PA,7581051.0,8120131.0,539080.0
7,AM,3483985.0,3941613.0,457628.0
8,CE,8451644.0,8794957.0,343313.0
9,ES,3514952.0,3833712.0,318760.0
10,MS,2449024.0,2757013.0,307989.0
11,PE,8796055.0,9058931.0,262876.0
12,DF,2572159.0,2817381.0,245222.0
13,PB,3766528.0,3974687.0,208159.0
14,MA,6574789.0,6776699.0,201910.0
15,RS,10693929.0,10882965.0,189036.0
16,RR,450479.0,636707.0,186228.0
17,PI,3119097.0,3271199.0,152102.0
18,SE,2067852.0,2210004.0,142152.0
19,RN,3168027.0,3302729.0,134702.0
20,TO,1383445.0,1511460.0,128015.0
21,BA,14017071.0,14141626.0,124555.0
22,AC,733559.0,830018.0,96459.0
23,RJ,15989929.0,16055174.0,65245.0
24,AP,669526.0,733759.0,64233.0
25,RO,1562409.0,1581196.0,18787.0
26,AL,3120887.0,3127683.0,6796.0
27,Fonte: IBGE. Diretoria de Pesquisas - DPE - C...,0.0,0.0,0.0
28,Nota: Para o cálculo das taxas de crescimento ...,0.0,0.0,0.0

In [20]:
populacao_estado.to_csv(
    "populacao_por_estado_crescimento.csv",
    sep=";",
    index=False
)

In [21]:
populacao_municipio = indicador_1.loc[:, [
    "UF",
    "COD. UF",
    "COD. MUNIC",
    "NOME DO MUNICÍPIO",
    "População 2010 (Alterações de Limites até 2022)1",
    "População Censo 2022"
]].copy()

# Calcular o crescimento
populacao_municipio["Crescimento"] = (
    populacao_municipio["População Censo 2022"]
    - populacao_municipio["População 2010 (Alterações de Limites até 2022)1"]
)

# Organizar do maior para o menor crescimento
populacao_municipio = populacao_municipio.sort_values(
    "Crescimento",
    ascending=False
).reset_index(drop=True)

populacao_municipio

,UF,COD. UF,COD. MUNIC,NOME DO MUNICÍPIO,População 2010 (Alterações de Limites até 2022)1,População Censo 2022,Crescimento
0,AM,13.0,2603.0,Manaus,1802014.0,2063689.0,261675.0
1,DF,53.0,108.0,Brasília,2572159.0,2817381.0,245222.0
2,SP,35.0,50308.0,São Paulo,11253503.0,11451999.0,198496.0
3,SP,35.0,52205.0,Sorocaba,586816.0,723682.0,136866.0
4,GO,52.0,8707.0,Goiânia,1301912.0,1437366.0,135454.0
...,...,...,...,...,...,...,...
5569,BA,29.0,27408.0,Salvador,2675656.0,2417678.0,-257978.0
5570,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5571,Nota: Para o cálculo das taxas de crescimento ...,NaN,NaN,NaN,NaN,NaN,NaN
5572,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5573,Fonte: IBGE. Diretoria de Pesquisas - DPE - C...,NaN,NaN,NaN,NaN,NaN,NaN

In [22]:
populacao_municipio.to_csv(
    "populacao_por_municipio_crescimento.csv",
    sep=";",
    index=False
)